const express = require('express')
const app = express()
const items = require('./api/routes')
const bodyParser = require('body-parser')
app.use(bodyParser.json())
app.use( bodyParser.urlencoded({extended: true}))
app.use(express.static('client'))
app.use('/tasks', items)
// app.post('/task/create', )
app.listen(3001)